### ISSUE TITLE
Use a global FUNDING.yml file

### ISSUE THREAD

**Issue by Hexstream** [vindarel/fuzzy-match#1]
I noticed that your FUNDING.yml file for this repo has not yet been updated to include [your GitHub Sponsors](https://github.com/sponsors/vindarel), but what you should really do is make a global FUNDING.yml file. [Here is an example](https://github.com/Hexstream/.github), and this links to the relevant documentation for this nice feature. After that, you just need to delete all repo-local FUNDING.yml files when you just want to use the global FUNDING.yml file, and enable the Sponsorships feature in the settings of the relevant repos.

**Comment by vindarel** [comment]
Thank you :) Done.

**Comment by Hexstream** [comment]
Awesome! You are welcome.

(You did not mention [your Patreon](https://www.patreon.com/vindarel), though? Is this intentional?)

**Comment by vindarel** [comment]
It is, now that I have GitHub sponsors I think Patreon doesn't have added value (unless you prove me wrong ;) ). And it has quite high taxes.

**Comment by Hexstream** [comment]
Right, in my case I'm still keeping my Patreon and linking to it just in case some people want to support me and already have a Patreon but not a GitHub, which would certainly be the case with a lot of non-developers.
